=head1 NAME

mRuby::State - state object for mRuby

=head1 DESCRIPTION

This is a perl representation of mrb_state.

=head1 METHODS

=over 4

=item my $state = mRuby::State->new() : mRuby::State

Create new instance of mRuby::State.

=item $state->parse_string($src : Str) : mRuby::ParserState

Parse ruby string and return new instance of L<mRuby::ParserState>.

=item $state->generate_code($parser_state : mRuby::ParserState) : Int

Generate code from L<mRuby::ParserState>.

=item $state->proc_new($n :Int) : mRuby::RProc

Get a L<mRuby::RProc> object from irep.

=item my $ret = $state->run($proc : mRuby::RProc, $val : Any) : Any

Run the C<< $proc >> and get a return value.

=back
